// ;not_working; import './src/mainPreImport';
// ;not_working;
// ;not_working; import { enableMapSet } from 'immer';
// ;not_working; enableMapSet();
// ;not_working;
// ;not_working; import * as immer from 'immer';
// ;not_working; immer.enableMapSet();
// ;not_working;
// ;not_working; const { enableMapSet } = require('immer');
// ;not_working;
// ;not_working; import { dummyExport_enableMapSet } from './src/mainPreImport';
// ;not_working; dummyExport_enableMapSet();